version: 2.1
jobs:
  test:
    resource_class: small
    docker:
      - image: cimg/node:20.5.1
    steps:
      - checkout
      - run:
          name: Test
          command: echo 1
  test2:
    resource_class: small
    docker:
      - image: cimg/node:20.5.1
    steps:
      - checkout
      - run:
          name: Test
          command: echo 2
  deploy:
    resource_class: small
    docker:
      - image: cimg/node:20.5.1
    steps:
      - checkout
      - run:
          name: Test
          command: exit $((RANDOM % 2))
workflows:
  version: 2
  ci:
    jobs:
      - test
      - test2
      - deploy:
          requires:
            - test
            - test2
