name: Test GH action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        run: sleep 2
      - name: Echo
        run: echo "Hello, world!"
      - name: Fail or not
        run: exit $((RANDOM % 2))
